name: Build VyOS LTS

on:
  push:
  schedule:
    - cron: '0 0 1 * *'  # Run build every month

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build vyos-build docker image
      run: |
        git clone -b crux --single-branch https://github.com/vyos/vyos-build
        cd vyos-build
        docker pull vyos/vyos-build:crux
        docker run --rm --privileged -v $(pwd):/vyos -w /vyos vyos-build:crux bash -c './configure --architecture amd64 --build-by "Hazaki" --build-type release 1.2.5 && sudo make iso'
    - name: Persist created iso
      uses: actions/upload-artifact@v1
      with:
        name: vyos-lts
        path: 'vyos-build/build/live-image-amd64.hybrid.iso'
