# This is a basic workflow to help you get started with Actions

name: VyOS-LTS

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Pull VyOS Docker image
      run: |
        git clone -b crux --single-branch https://github.com/vyos/vyos-build
        docker pull vyos/vyos-build:crux
    - name: Build iso
      run: |
        docker run --rm --privileged -v $(pwd)/vyos-build:/vyos -w /vyos vyos/vyos-build:crux  bash -c './configure --architecture amd64 --build-by "Hazaki" --build-type release --version 1.2.5 && sudo make iso'
    - name: Persist created iso
      uses: actions/upload-artifact@v2
      with:
        name: vyos-lts
        path: 'vyos-build/build/live-image-amd64.hybrid.iso'
