name: VyOS-LTS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Pull VyOS Docker image
      run: |
        git clone -b current --single-branch https://github.com/vyos/vyos-build
        docker pull vyos/vyos-build:current
    - name: Build iso
      run: |
        docker run --rm --privileged -v $(pwd)/vyos-build:/vyos -w /vyos vyos/vyos-build:current  bash -c './configure --architecture amd64 --build-by "Hazaki" --build-type release --version 1.3.0 && sudo make iso'
    - name: Persist created iso
      uses: actions/upload-artifact@v2
      with:
        name: vyos-lts
        path: 'vyos-build/build/live-image-amd64.hybrid.iso'
